### ISSUE TITLE
Recreate repo with template

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-connectivity#1]
Hi @larsoner I just realized there is a men-python template repository. Any chance you can delete this one and I can go ahead and recreate the repo?

**Comment by larsoner** [comment]
I'm not sure how up to date that is, it might be better to just grab what you need from mne-nirs or mne-bids, both of which are a good combination of kept-up-to-date and also close to what MNE-Python does. Actually looking at it I would say MNE-Realtime has the closest structure (testing Windows on Azure, Linux/macOS on GH Actions, and building docs with CircleCI). So I would just copy some of those files over, edit them, start pushing commits, and iterate until you get all green CIs on `pytest mne_connectivity`, and to start I would make a `mne_connectivity/tests/*` a literal copy-paste from `mne/connectivity/tests/*`. 

That way you get all of the testing and CI infrastructure working first. Next I would port `mne.connectivity` code into the `mne_connectivity` namespace however you're planning to do it, and replace `mne.connectivity.*` in the tests with `mne_connectivity.*` as you port things over.

WDYT?

**Comment by adam2392** [comment]
Okay sounds good! I will just use the `mne-realtime` template then. I'll get all this started in one PR to handle the "official refactoring step then".
