### ISSUE TITLE
Unclear how to load connectivity object from disk after saving it

### ISSUE THREAD

**Issue by moritz-gerster** [mne-tools/mne-connectivity#134]
#### Describe the bug
The connectivity class enables saving connectivity objects to disk via the [save method](https://mne.tools/mne-connectivity/stable/generated/mne_connectivity.Connectivity.html#mne_connectivity.Connectivity.save).

Saving works, however, I cannot load the data once saved. The documentation of that method is not very helpful. It is not clear in which file format the connectivity should be saved and with what function it should be loaded. 

I expected to save it as a ".fif" file and loading it using mne.io.read_raw(file). This didn't work. Looking at the code I realized it's supposed to be saved as a ".nc" file. However, loading the ".nc" file using netCDF also didn't work. Please refer to my [jupyter notebook](https://github.com/mne-tools/mne-connectivity/files/10983967/mne_bug_connectivity.pdf) for examples. 

#### Steps to reproduce
I used the code from [this tutorial](https://mne.tools/mne-connectivity/stable/auto_examples/sensor_connectivity.html#sphx-glr-auto-examples-sensor-connectivity-py) to show my failed efforts in this [jupyter notebook](https://github.com/mne-tools/mne-connectivity/files/10983967/mne_bug_connectivity.pdf) to reproduce the issue.

#### Expected results
The documentation should tell me how to save and how to load the connectivity object. Once loaded, I can work with it and extract all data.

#### Actual results
Loading the file returns
```Python
RuntimeError: NetCDF: Can't open HDF5 attribute
```

#### Additional information
```Python
Platform:         macOS-13.2.1-arm64-arm-64bit
Python:           3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:26:40) [Clang 14.0.6 ]
Executable:       /Users/moritzgerster/anaconda3/envs/bids_neu/bin/python
CPU:              arm: 10 cores
Memory:           16.0 GB

mne:              1.3.0
numpy:            1.23.4 {OpenBLAS 0.3.21 with 10 threads}
scipy:            1.9.3
matplotlib:       3.6.2 {backend=module://matplotlib_inline.backend_inline}

sklearn:          1.1.3
numba:            Not found
nibabel:          5.0.1
nilearn:          Not found
dipy:             Not found
openmeeg:         Not found
cupy:             Not found
pandas:           1.5.1
pyvista:          0.38.4 {OpenGL 4.1 Metal - 83 via Apple M1 Pro}
pyvistaqt:        0.9.1
ipyvtklink:       Not found
vtk:              9.2.5
qtpy:             2.3.0 {PyQt5=5.15.6}
ipympl:           Not found
pyqtgraph:        Not found
pooch:            v1.6.0

mne_bids:         0.12
mne_nirs:         Not found
mne_features:     Not found
mne_qt_browser:   Not found
mne_connectivity: 0.5.0
mne_icalabel:     Not found

```

**Comment by ruuskas** [comment]
Hi @moritz-gerster! I believe you should use the [`mne_connectivity.read_connectivity`](https://mne.tools/mne-connectivity/stable/generated/mne_connectivity.read_connectivity.html) function.

**Comment by moritz-gerster** [comment]
> Hi @moritz-gerster! I believe you should use the [`mne_connectivity.read_connectivity`](https://mne.tools/mne-connectivity/stable/generated/mne_connectivity.read_connectivity.html) function.

That makes sense and it works - thanks!

**Comment by moritz-gerster** [comment]
I think the documentation should be updated. I did not figure this out on my own. There is no example showing this.

**Comment by adam2392** [comment]
Seems like the docs could be more clear tho if you had a tough time figuring it out. Interested in making a PR to clarify the docs/docstrings @moritz-gerster?
