### ISSUE TITLE
[Doc] Drop-down version selection menu is not working on the 0.6.0 dev documentation

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-connectivity#143]
On the dev documentation https://mne.tools/mne-connectivity/dev/index.html, the dropdown version selection menu does not work. It does work on the stable documentation https://mne.tools/mne-connectivity/stable/index.html

**Comment by larsoner** [comment]
MNE-Python appears not to have this problem so I'd start looking at the differences between the to `conf.py` / `versions.json`s

**Comment by mscheltienne** [comment]
Same issue with `mne-icalabel` by the way :disappointed:

**Comment by drammock** [comment]
I'm working on a fix for mne-connectivity right now
