### ISSUE TITLE
Slate v0.6 for release

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-connectivity#146]
After #142 is merged.

FYI @tsbinns

**Comment by adam2392** [comment]
Now that the dev process got modernized, we can slate a release I guess?

Anything we want to add beforehand?

cc: @tsbinns @drammock @larsoner @britta-wstnr

**Comment by larsoner** [comment]
Sounds good to me

**Comment by adam2392** [comment]
New release is on pypi: https://pypi.org/project/mne-connectivity/
