### ISSUE TITLE
Examples not rendering properly for v0.6 documentation

### ISSUE THREAD

**Issue by tsbinns** [mne-tools/mne-connectivity#165]
Not sure if people are aware of this, but the examples are not rendering properly for the [v0.6 documentation](https://mne.tools/mne-connectivity/stable/auto_examples/index.html), specifically there is no output from the cells.

E.g. no plotting after calling `plt.show()`
<img src="https://github.com/mne-tools/mne-connectivity/assets/56922019/a2b8bfb8-72c2-4a83-b9a1-e84fae833395" width="70%" height="70%">

E.g. no logging output
<img src="https://github.com/mne-tools/mne-connectivity/assets/56922019/0b597df5-bceb-4a29-8949-79e743b7617e" width="70%" height="70%">

The same thing is happening for all v0.6 examples.

This is not the case for the [dev branch examples](https://mne.tools/mne-connectivity/dev/auto_examples/index.html), where everything works as before.

##

In case help is wanted I am happy to try and lend a hand!

**Comment by larsoner** [comment]
This is very weird since it looks like the CircleCI build that was used did not raise an error or anything:

https://app.circleci.com/pipelines/github/mne-tools/mne-connectivity/834/workflows/4d220ca5-2c89-4c37-be78-492f49581df6/jobs/898

I'll try pushing an empty commit to `maint/0.6` and we can see if it fixes it

**Comment by larsoner** [comment]
I think the problem might have been https://github.com/mne-tools/mne-connectivity/commit/50fac84a39017aa41fb14f2d44fd5b44053f95d8, let's see if it fixes things in the next ~10-15 minutes...

**Comment by larsoner** [comment]
Looks like it's now fixed!
