### ISSUE TITLE
[BUG] n_jobs=-1 not working in spectral_connectivity_epochs

### ISSUE THREAD

**Issue by tsbinns** [mne-tools/mne-connectivity#176]
#### Describe the bug
Setting `n_jobs=-1` for `spectral_connectivity_epochs()` fails to parallelise computation of the CSD over epochs.

If `n_jobs=-1`, `parallel_func()` is called to create an `_epoch_spectral_connectivity()` function associated with the appropriate number of workers from `multiprocessing.cpu_count()`.
https://github.com/mne-tools/mne-connectivity/blob/f9a2e658bcf05c6af61b937798a3b2e11e187599/mne_connectivity/spectral/epochs.py#L914-L917

However, when subsequently creating the epoch blocks to compute the CSD for in parallel, `_get_n_epochs()` does not convert `n_jobs=-1` to the maximum number of workers, which results in each epoch block only consisting of a single epoch, which are passed into the parallelised `_epoch_spectral_connectivity()` function one-by-one.
https://github.com/mne-tools/mne-connectivity/blob/f9a2e658bcf05c6af61b937798a3b2e11e187599/mne_connectivity/spectral/epochs.py#L991

#### Steps to reproduce
```
from multiprocessing import cpu_count
import numpy as np
from mne_connectivity import spectral_connectivity_epochs

n_epochs = 10
n_chans = 2
n_times = 100
sfreq = 50
data = np.random.rand(n_epochs, n_chans, n_times)

spectral_connectivity_epochs(data, sfreq=sfreq, n_jobs=cpu_count())
spectral_connectivity_epochs(data, sfreq=sfreq, n_jobs=-1)
```

#### Expected results
Both `n_jobs=cpu_count()` and `n_jobs=-1` should parallelise CSD computation over epochs.

#### Actual results
`n_jobs=cpu_count()` parallelised CSD computation over epochs as expected. E.g. with 16 workers on my machine I get the following logging output:
![image](https://github.com/mne-tools/mne-connectivity/assets/56922019/15dc4184-fb00-4dad-adf2-cdb2c545cf2f)

`n_jobs=-1` allocates multiple workers to `_epoch_spectral_connectivity()`, but only passes in the data of one epoch at a time. E.g. I get the following logging output:
![image](https://github.com/mne-tools/mne-connectivity/assets/56922019/00d5c90d-5e88-40bf-977f-c12d7f26c72d)

#### Bug fix
Fixing this is simply a case of having `parallel_func()` return `n_jobs` as the third output.
https://github.com/mne-tools/mne-connectivity/blob/f9a2e658bcf05c6af61b937798a3b2e11e187599/mne_connectivity/spectral/epochs.py#L914-L917

#### Additional information
`mne.sys_info()` output:

Platform             Windows-10-10.0.22631-SP0
Python               3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:27:59) [MSC v.1937 64 bit (AMD64)]
Executable           C:\Users\tsbin\anaconda3\envs\mne_connectivity_dev\python.exe
CPU                  Intel64 Family 6 Model 154 Stepping 3, GenuineIntel (16 cores)
Memory               31.7 GB

Core
├☑ mne               1.6.1 (unable to check for latest version on GitHub, timeout after 2.0 sec)
├☑ numpy             1.24.3 (OpenBLAS 0.3.21 with 16 threads)
├☑ scipy             1.10.1
├☑ matplotlib        3.7.1 (backend=QtAgg)
├☑ pooch             1.7.0
└☑ jinja2            3.1.2

Numerical (optional)
├☑ sklearn           1.2.2
├☑ nibabel           5.1.0
├☑ nilearn           0.10.1
├☑ pandas            2.0.1
└☐ unavailable       numba, dipy, openmeeg, cupy

Visualization (optional)
├☑ pyvista           0.39.1 (OpenGL 4.5.0 - Build 31.0.101.4575 via Intel(R) Iris(R) Xe Graphics)
├☑ pyvistaqt         0.10.0
├☑ vtk               9.2.6
├☑ qtpy              2.3.1 (PyQt6=6.6.0)
├☑ pyqtgraph         0.13.3
├☑ mne-qt-browser    0.5.0
└☐ unavailable       ipympl, ipywidgets, trame_client, trame_server, trame_vtk, trame_vuetify

Ecosystem (optional)
├☑ mne-bids          0.13.dev0
├☑ mne-connectivity  0.7.0.dev0
└☐ unavailable       mne-nirs, mne-features, mne-icalabel, mne-bids-pipeline

**Comment by tsbinns** [comment]
Credit to @richardkoehler for discovering this!

**Comment by larsoner** [comment]
Probably this
```
parallel, my_epoch_spectral_connectivity, _ = parallel_func( 
```
should be changed to this
```
parallel, my_epoch_spectral_connectivity, n_jobs = parallel_func( 
```
it will change `n_jobs = -1` to `n_jobs = cpu_count()` effectively (the `parallel_func` deals with the `-1` under the hood)

https://github.com/mne-tools/mne-python/blob/90067893e330c1941c055be22bc5f442ad320ec3/mne/parallel.py#L77-L78

**Comment by tsbinns** [comment]
Yes, I am just writing a PR now.
