### ISSUE TITLE
For envelope_correlation get rid of "combine" parameter and add it as a function to the Connectivity class

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-connectivity#18]
From an API standpoint, I wonder if we should get rid of `combine` as a function argument here and add it as a method of `EpochsTemporalConnectivity` that you can call to combine to obtain a TemporalConnectivity.

And it actually seems like there are some classes missing, like EpochConnectivity and then Connectivity that have no time space or frequency dims.

In other words, I think this should return an instance of EpochConnectivity, and that class should have a method `.combine` that returns a `Connectivity`

_Originally posted by @larsoner in https://github.com/mne-tools/mne-connectivity/pull/6#discussion_r665428841_

**Comment by britta-wstnr** [comment]
+1 from me, also allows more flexibility in analysis pipelines.
