### ISSUE TITLE
v0.7 documentation unavailable

### ISSUE THREAD

**Issue by tsbinns** [mne-tools/mne-connectivity#207]
The documentation is still using the build from v0.6 as the stable version, so the docs for v0.7 are not available online.

@larsoner mentioned in https://github.com/mne-tools/mne-connectivity/issues/181#issuecomment-2163340142
> In theory CircleCI should try to push 0.7 to https://mne.tools/mne-connectivity/stable soon!

but a week on that hasn't happened.

Any way for this push to be triggered?
Cheers!

**Comment by larsoner** [comment]
Argh I forgot to `git push upstream -u maint/0.7`. Just did it, though, let's see if it succeeds :crossed_fingers:
