### ISSUE TITLE
Don't plot nan values in mne-connectivity.viz.plot_connectivity_circle

### ISSUE THREAD

**Issue by JohannesWiesner** [mne-tools/mne-connectivity#249]
If your issue is a usage question, please consider asking on the
[MNE Forum](https://mne.discourse.group) instead of opening an issue.

#### Describe the problem

Currently, mne-connecvitiy.viz.plot_connectivity_circle seems to interpret nan-values as 0s. Would be nice if a connection line would not be plotted at all if the connection between two nodes is np.nan.

**Comment by tsbinns** [comment]
Hi @JohannesWiesner,

I am not able to replicate this behaviour. E.g., here I create an example connectivity matrix and set the connectivity between nodes 0 and 1 to be `np.nan`:

```
import numpy as np
from mne_connectivity.viz import plot_connectivity_circle

n_cons = 5
data = np.random.rand(n_cons, n_cons)
data[np.arange(n_cons), np.arange(n_cons)] = 1  # set diag to 1
data[np.triu_indices(n_cons, 1)] = data.T[np.triu_indices(n_cons, 1)]  # make symmetric
data[1, 0] = np.nan  # set 0-1 to NaN

plot_connectivity_circle(data, node_names=[f"Node {i}" for i in range(n_cons)])
```

If I run this code, I don't see any line between nodes 0 and 1.

Internally, a threshold for connectivity values to plot is determined, which values like `np.nan` will never meet, so they get discarded.

I wonder if somewhere in your code NaNs are being converted to zeros? Do you have an example you could share?
