### ISSUE TITLE
Should mne_connectivity.spectral have an option to not “combine”?

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-connectivity#26]
Inside mne_connectivity.spectral_connectivity, all functions assume that Epochs are samples of the same connectivity structure. That is, they average over Epochs implicitly in the function.

The code is a bit harder to parse through, but wondering if it is worth the effort to also, allow it to return an `EpochSpectroTemporalConnectivity`, rather then `SpectroTemporalConnectivity` to allow the user some flexibility of later "combining" over epochs with median/mean/etc?

**Comment by larsoner** [comment]
All of the spectral estimators IIRC currently collapse across epochs to make their estimates (i.e., there is no estimate of connectivity for an individual epoch), so I don't see a way to do this.

**Comment by larsoner** [comment]
(and currently I don't think they'd return `SpectroTemporalConnectivity` but rather just `SpectralConnectivity` even now, since the temporal dimension is converted / changed to spectral domain?)

**Comment by adam2392** [comment]
This is now closed by #69 and #67 introducing spectral connectivity over time.
