### ISSUE TITLE
Add option to set colorbar ticks and label in `plot_connectivity_circle`

### ISSUE THREAD

**Issue by ruuskas** [mne-tools/mne-connectivity#262]
#### Describe the problem
The connectivity circle visualization function currently does not allow much control over the colorbar. I think many users might want to set a label for the colorbar and control the tick locations to produce figures closer to publication quality. It appears somewhat difficult to change these and find the colorbar instance after the figure is created.

#### Describe your solution
It's very simple of course. I can make a PR adding a few parameters to the plotting function here and in `mne.viz.circle` if this is something others consider valuable. Perhaps something like `colorbar_ticks` and `colorbar_label`.

**Comment by larsoner** [comment]
I am more inclined to teach users how to find a colorbar for any matplotlib figure, since there are lots of things you might want to set (title, ticks, spacing, etc.). Did you find any reasonable / reliable way to get the colorbar axes? Maybe it just lives in `fig.axes[-1]`?

**Comment by ruuskas** [comment]
It does live in `fix.axes[-1]`, but getting the `Colorbar` object out of the `Axes` does not seem trivial. Perhaps I'm not good enough at Googling, but I'm failing to find a way to manipulate it after no longer having a direct pointer to the colorbar.

I agree that it might be worth it expanding the tutorials. I don't know what would be a reasonable level though. There are quite many steps to make figures like the one below. My workaround to manipulate the colorbar has been to just make the necessary tweaks to `plot_connectivity_circle` locally. 

Perhaps we could add a `colorbar_kwargs` parameter to avoid cluttering the API?

![example_con](https://github.com/user-attachments/assets/bb55f337-64dc-4f5c-8eb7-7227ae9f1465)

**Comment by ruuskas** [comment]
> At least for images you can do for example

This approach doesn't seem to work for the `PolarAxes`, or at least I could not find the colorbar while looking into what's inside `fig.axes[0]`. 

> That would be okay. Another option that might be even better (?) would be to add a fig.mne which is just a Bunch object. And we can have a fig.mne.colorbar. We do this sort of thing to keep track of stuff in our matplotlib-based figures sometimes. It seems a bit more flexible than the colorbar_kwargs because then you have access to all methods of the colorbar itself, which is nice.

This sounds good to me. I can test whether it works as expected and then make a PR. I think it's necessary to somehow indicate in the docstring of `plot_connectivity_circle` that this exists so that others can find it.

**Comment by drammock** [comment]
> I can test whether it works as expected and then make a PR

Question for @larsoner about the implementation: why `Bunch` instead of, e.g., `SimpleNamespace` or `DataClass`?  Is it somehow important that both `.attr` and `["attr"]` access work?

**Comment by larsoner** [comment]
Those would probably be better, I just forget about them!
