### ISSUE TITLE
Time-Resolved Spectral Connectivity PLI implementation

### ISSUE THREAD

**Issue by christian-oreilly** [mne-tools/mne-connectivity#30]
#### Describe the bug

I think the implementation of the PLI metric is wrong. The standard definition is:
```
PLI=|mean(sign(difference_in_instantaneous_phase))|
```
Note that for a signal of N time samples, this PLI value is obtained as the average of N values. The MNE implementation of this metric follows the implementation of Ortiz and instead of computing this metric in the time domain (e.g. using the Hilbert transform to estimate the instantaneous phase) computes it in the frequency domain using the cross-spectrum. An issue arise when this passage to the frequency domain is used to analyze the PLI results at the individual frequency bands. For example, the default behavior of `spectral_connectivity()` is `faverage=False`, which therefore report a value for each frequency. In this case, the PLI estimate that was the absolute-mean-value of N samples become the absolute-mean-value of 1 sample... so the PLI estimates reduce to 0 or 1 (where it was originally a value taken from the {0/N, 1/N, 2/N, ..., N/N}). Now, if we might think that we would recover the correct values using `faverage=True`, but we don't because this computes the mean-absolute-value, not the absolute-mean-value... Here is a part of the `spectral_connectivity()` code:

```python
    for method, n_args in zip(con_methods, n_comp_args):
        # future estimators will need to be handled here
        if n_args == 3:
            # compute all scores at once
            method.compute_con(slice(0, n_cons), n_epochs)
        elif n_args == 5:
            # compute scores block-wise to save memory
            for i in range(0, n_cons, block_size):
                con_idx = slice(i, i + block_size)
                psd_xx = psd[idx_map[0][con_idx]]
                psd_yy = psd[idx_map[1][con_idx]]
                method.compute_con(con_idx, n_epochs, psd_xx, psd_yy)
        else:
            raise RuntimeError('This should never happen.')

        # get the connectivity scores
        this_con = method.con_scores

        if this_con.shape[0] != n_cons:
            raise ValueError('First dimension of connectivity scores must be '
                             'the same as the number of connections')
        if faverage:
            if this_con.shape[1] != n_freqs:
                raise ValueError('2nd dimension of connectivity scores must '
                                 'be the same as the number of frequencies')
            con_shape = (n_cons, n_bands) + this_con.shape[2:]
            this_con_bands = np.empty(con_shape, dtype=this_con.dtype)
            for band_idx in range(n_bands):
                this_con_bands[:, band_idx] =\
                    np.mean(this_con[:, freq_idx_bands[band_idx]], axis=1)
            this_con = this_con_bands
```
Note that the `faverage` part comes after the call to `compute_con()` which, in the case of `_PLIEst` already applied the absolute operator. So, whereas in the definition, you average N values taken in {-1, 0, 1}, here you average N values taken in {0, 1}.

If I am not mistaken, the function "appears" to work when using epochs because then it does the `mean(signs(X))` across the M epochs, before computing the absolute value. But remember that the stuff in X was initially N values saying whether the time-lag at every N time samples was positive or negative. Now X values are still saying whether the phase-difference is positive or negative, but you traded the ability to check it at every time point to have it localized in frequencies (uncertainty principle), so you have just one value per epochs and you average it across M epochs. I might have interesting properties on its own, but I don't think it is still fair to call this a PLI measure, i.e. average_across_epochs(abs(average_across_x)) != average_across_x(abs(average_across_epochs)) (where x can be either time or frequency, depending on whether you transform from temporal representation to frequency).

**Comment by juancamiload** [comment]
Perhaps the implementation in [HyPyP](https://github.com/ppsp-team/HyPyP) may help?
e.g., https://github.com/ppsp-team/HyPyP/blob/a7f78ef9886ca0621b0d2b5d5650eb1d8c903fc8/hypyp/analyses.py#L398

**Comment by adam2392** [comment]
Hi @Avoide I think the latest commit on `main` might have this resolved with the PR #104. WDYT?

**Comment by Avoide** [comment]
> Hi @Avoide I think the latest commit on `main` might have this resolved with the PR #104 and #115. WDYT?
> 
> https://github.com/mne-tools/mne-connectivity/blob/ed40aefa286b0d1522937d8b9665ec1218ee262c/mne_connectivity/spectral/time.py#L202-L204

Hi @adam2392. I had a look at the PRs and also tested the functions from the newest (dev) version of mne-connectivity on the simulated toy-examples from my earlier response in this Issue, and got the expected output! (Low connectivity over time, around 0.1-0.2 PLV/wPLI for random data, while more than 0.97 PLV/wPLI for a sinus wave), so I agree this have now been resolved.

Great work @ruuskas! It was also much easier to use the functions compared to when I last tested them, with the new API. The only minor discrepancy I noticed was that in spectral_connectivity_epochs, the freqs are automatically calculated when I input fmin and fmax, while in spectral_connectivity_time you are required to specify freqs, despite giving fim and fmax.

**Comment by ruuskas** [comment]
> The only minor discrepancy I noticed was that in spectral_connectivity_epochs, the freqs are automatically calculated when I input fmin and fmax, while in spectral_connectivity_time you are required to specify freqs, despite giving fmin and fmax.

Hi @Avoide! Good to hear that it's also working for you.
The reason `spectral_connectivity_time` requires `freqs` is that setting them automatically is quite arbitrary and could potentially even lead to misinterpretation of the results. I would say that a 1 Hz grid is a good starting point.

**Comment by adam2392** [comment]
Yeah good point, we should probably consolidate the API to require freqs for both. WDYT @larsoner ? I think we could still support `freqs = 'auto'` but perhaps now freqs should be a required parameter?

**Comment by ruuskas** [comment]
This is just my take, but as far as I understand that wouldn't be possible or practical.

Freqs is already required with `spectral_connectivity_epochs` in the Morlet wavelet mode. In the multitaper and Fourier modes, the spectrum is computed using `scipy.fft.rfft`, which does not allow specifying `freqs`.

**Comment by adam2392** [comment]
I'm going to close this issue then as resolved. If there's more API discussion to be had regarding `spectral_connectivity_epochs`, we can open another issue.
