### ISSUE TITLE
v0.2 release

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-connectivity#34]
A release with the VAR models and connectivity classes and improved documentation.

**Comment by larsoner** [comment]
You will need to update MNE-Python almost immediately thereafter, I currently get for example:
```
WARNING: /home/larsoner/python/mne-python/tutorials/epochs/60_make_fixed_length_epochs.py failed to execute correctly: Traceback (most recent call last):
  File "/home/larsoner/python/mne-python/tutorials/epochs/60_make_fixed_length_epochs.py", line 100, in <module>
    corr_matrix = envelope_correlation(alpha_data, combine=None)
TypeError: envelope_correlation() got an unexpected keyword argument 'combine'
```

**Comment by larsoner** [comment]
(and the output type will have changed, so that'll need to be updated there, etc.)

**Comment by adam2392** [comment]
Sounds good. I will slate a 0.2 release, once we get the main docs sorted out
