### ISSUE TITLE
parameter "names" not documented in spectral_connectivity docstring

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-connectivity#38]
![Screenshot_2021-09-08_11-13-28](https://user-images.githubusercontent.com/1810515/132546223-cb0115bf-de43-4ea6-8b9e-686379e834b4.png)

This is on current `main`

**Comment by larsoner** [comment]
This indicates two problems: 1) the specific one mentioned here, and 2) that `numpydoc` checks are not enabled during doc build, which would have caught this.
