### ISSUE TITLE
Sphinx docs gallery: "There is still something wrong with the scraping"

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-connectivity#5]
There is still something wrong with the scraping:

https://29-369628653-gh.circle-artifacts.com/0/dev/auto_examples/index.html

Do you want help fixing that? It's probably a pain...

_Originally posted by @larsoner in https://github.com/mne-tools/mne-connectivity/issues/4#issuecomment-862634372_

**Comment by larsoner** [comment]
I'll take a look early next week. In the meantime it's hopefully not a blocker

**Comment by adam2392** [comment]
So I'm having trouble building the docs locally on my Mac and on my Linux workstation (surprisingly)... Basically it's hung on the `mne_inverse_envelope_correlation.py` sphinx generation of the gallery step. It's fired up all the other plots successfully. I followed the men-python installation steps, so not sure if I'm just messing things up. Everything else, style, unit tests and such all work.

I was wondering if you have any advice on how to make a release then if I can't upload the docs as specified here: https://github.com/mne-tools/mne-bids/wiki/How-to-make-a-release?

Is there a way to "deploy the docs" via a CI build instead, which at least seems to work, so I can proceed w/ the release?

**Comment by larsoner** [comment]
Yes I would set up CIs to m manually upload docs, it's what we do in MNE-Python and I'm not sure why BIDS did not follow suit. I'll take a look on Monday I wouldn't worry about cutting a first release + docs until next week at the earliest.

**Comment by adam2392** [comment]
Closed via #12
