### ISSUE TITLE
Label orientation in plot_connectivity_circle()

### ISSUE THREAD

**Issue by alexanderkroner** [mne-tools/mne-connectivity#59]
#### Describe the bug
I encountered a possible issue with `plot_connectivity_circle()`. When executing `test_plot_connectivity_circle()` with `start_pos=0` instead of `start_pos=90`, the following figure is created:

![test](https://user-images.githubusercontent.com/23718725/145681151-9d0d6fe2-f9de-4bda-9471-83aa41a35ac5.png)

The orientation of labels in the upper right quadrant might not be desired behavior. If you agree with this then a simple fix would be to insert `if angle_deg >= 270 or angle_deg < 90` at this line:

https://github.com/mne-tools/mne-connectivity/blob/f3ff4ed9bb76dd28248f5944bb7abf875ca38b1d/mne_connectivity/viz/circle.py#L319

**Comment by drammock** [comment]
Seems like a sensible change to me! Can you make a pull request with your proposed fix?
