### ISSUE TITLE
Adding AR model / linear system over sliding windows as a time-varying connectivity method

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-connectivity#7]
As mentioned in the original GSoC proposal and also in MNE-Python, this would be a fit to the data using the model:

```
x(t+1) = Ax(t)
```

over small time windows. This is a generative model and so can be accompanied by a tutorial showing "reconstruction" of the ieeg data.

**Comment by agramfort** [comment]
Don’t write this code from scratch 

Use existing code for fitting MVAR models

**Comment by adam2392** [comment]
I think the best existing code could be maybe sklearns multivariate linear regression code?

**Comment by agramfort** [comment]
no. sklearn is not a time series package.

you have https://www.statsmodels.org/dev/vector_ar.html
and https://github.com/scot-dev/scot/blob/master/scot/var.py

ping @cbrnr

**Comment by cbrnr** [comment]
[SCoT](https://github.com/scot-dev/scot) has all the basic time-varying AR estimation set up. I haven't had time to work on it in the past years, but it is a great package and supports many connectivity measures based on AR coefficients. I'd be happy if we found a way to revive the package, which could even mean transferring it to a new repo and then extending/adapting/updating the code base (it is MIT licensed so there's no problem).

**Comment by agramfort** [comment]
yes +100 to integrate SCoT into mne-connectivity

>
