### ISSUE TITLE
Add conda-forge package?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-connectivity#78]
Hello, I just wanted to ask if you'd be interested in a `conda-forge` package of MNE-Connectivity? I could build one.

Asking because I'm right now looking at packages that would be nice to include in the [MNE installers](https://github.com/hoechenberger/mne-installers).

**Comment by larsoner** [comment]
Good idea, feel free to do it @hoechenberger !

**Comment by hoechenberger** [comment]
WIP: https://github.com/conda-forge/staged-recipes/pull/17982

It seems the conda-forge CI system is experiencing some trouble right now.

**Comment by hoechenberger** [comment]
The package has been added and should soon be installable via `conda install -c conda-forge mne-connectivity`

**Comment by hoechenberger** [comment]
Maybe the install instructions should mention `conda` too?

**Comment by adam2392** [comment]
Cool thanks @hoechenberger !

Is there a good way to update this for each release? / instructions?

**Comment by hoechenberger** [comment]
> Is there a good way to update this for each release? / instructions?

There's actually a bot taking care of this :) Unless dependencies change and building & importing the package fails 😅 then we have to manually intervene
