### ISSUE TITLE
MAINT: Release?

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-connectivity#85]
@adam2392 are you up for cutting a new release of mne-connectivity? That would make it easier to include it in the standalone installer for MNE-Python.

Or if you have a release process you generally follow documented somewhere, I could take a stab at it. Or if it's not documented, I can also do it if the process is just 1) change version, commit, push; 2) release on Github; 3) push to PyPi; 4) push to maint/0.3; 5) change version to next dev and push.

**Comment by adam2392** [comment]
Sure I was originally going to wait for #73 to get sorted out, but if it's a blockage for MNE-Python, we can do so now.

I just follow the mne-bids release process :p. Is that sufficient?

**Comment by larsoner** [comment]
Yeah it would be good to push one out, mne-bids process should be fine!

**Comment by adam2392** [comment]
Sorry I'm in vacation with my family. Coming back tonight and will try to slate a release then.

**Comment by hoechenberger** [comment]
Amazing, thank you! Enjoy the rest of your vacation 🏝

**Comment by adam2392** [comment]
I just made a release. @hoechenberger and @larsoner
